# Data Preprocessing Tools

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
df = pd.read_csv('Data.csv')
# We want to create a matrix of features (independent variables) and the dependent variable vector

# Features
# We want X to be all the columns except the last one because that is how commonly a dataset is created. 
X = df.iloc[:,:-1].values

# Dependent Variable
Y = df.iloc[:, -1].values


In [26]:
print(X)
print(type(X))
print(type(X[0]))

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
print(Y)
print(type(Y))
print(type(Y[0]))

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
<class 'numpy.ndarray'>
<class 'str'>


## Taking care of missing data

In [0]:
from sklearn.impute import SimpleImputer

"""We want to create a imputer object
 This instance of SimpleImputer replaces all nan into the mean of the values"""
 
si = SimpleImputer(missing_values=np.nan, strategy = "mean")

si.fit(X[:,1:3])
# Transform method returns a new value
X[:,1:3] = si.transform(X[:,1:3])


## Encoding categorical data

### Encoding the Independent Variable

In [0]:
# We want to turn the strings into numbers without having the machine misinterperting the numerical data
# Therefore we would use one hot encoding, transforming the country column into a matrix 
# (for example France would be (1,0,0) and Span (0,1,0) etc.)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [32]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### Encoding the Dependent Variable

In [0]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)

In [37]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split

# Recommended split = 0.8 train and 0.2 test
X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)


In [41]:
print(X_train)

X Train
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [42]:
print(X_test)

X Test
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [43]:
print(Y_train)

Y Train
[0 1 0 0 1 1 0 1]


In [44]:
print(Y_test)

Y Test
[0 1]


## Feature Scaling

In [0]:
# We are using the standardization method of feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
# We don't need to apply feature scaling on the dummy variables. 

X_train[:, 3:] = sc.fit_transform(X_train[:,3:]) # Fit only calculates the standardization, and transform actually transforms it
X_test[:, 3:] = sc.transform(X_test[:,3:]) # We only use transform so we don't get a different fit scalar than the training set


In [47]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [48]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
